// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hash struct {
	Hash string `json:"hash"`
}

type Url struct {
	Hash      string           `json:"hash"`
	Url       string           `json:"url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
