// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForSaveAllHashes implements pgx.CopyFromSource.
type iteratorForSaveAllHashes struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForSaveAllHashes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveAllHashes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForSaveAllHashes) Err() error {
	return nil
}

func (q *Queries) SaveAllHashes(ctx context.Context, hash []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"hash"}, []string{"hash"}, &iteratorForSaveAllHashes{rows: hash})
}
