// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CountCaches(ctx context.Context) (int64, error)
	CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (Url, error)
	DeleteShortUrlBeforeCreatedAt(ctx context.Context, arg DeleteShortUrlBeforeCreatedAtParams) ([]string, error)
	FindUrlByHash(ctx context.Context, hash string) (string, error)
	GetHashBatch(ctx context.Context, limit int32) ([]string, error)
	GetUniqueNumbers(ctx context.Context, generateSeries int64) ([]int64, error)
	SaveAllHashes(ctx context.Context, hash []string) (int64, error)
}

var _ Querier = (*Queries)(nil)
