// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url_query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCaches = `-- name: CountCaches :one
SELECT COUNT(*)
FROM hash
`

func (q *Queries) CountCaches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCaches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortUrl = `-- name: CreateShortUrl :one
INSERT INTO url (hash, url)
VALUES ($1, $2) RETURNING hash, url, created_at
`

type CreateShortUrlParams struct {
	Hash string `json:"hash"`
	Url  string `json:"url"`
}

func (q *Queries) CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createShortUrl, arg.Hash, arg.Url)
	var i Url
	err := row.Scan(&i.Hash, &i.Url, &i.CreatedAt)
	return i, err
}

const deleteShortUrlBeforeCreatedAt = `-- name: DeleteShortUrlBeforeCreatedAt :many
DELETE
FROM url
WHERE url.created_at < $1
  AND hash IN (SELECT hash FROM url LIMIT $2)
    RETURNING hash
`

type DeleteShortUrlBeforeCreatedAtParams struct {
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Limit     int32            `json:"limit"`
}

func (q *Queries) DeleteShortUrlBeforeCreatedAt(ctx context.Context, arg DeleteShortUrlBeforeCreatedAtParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteShortUrlBeforeCreatedAt, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUrlByHash = `-- name: FindUrlByHash :one
SELECT url
FROM url
WHERE hash = $1 LIMIT 1
`

func (q *Queries) FindUrlByHash(ctx context.Context, hash string) (string, error) {
	row := q.db.QueryRow(ctx, findUrlByHash, hash)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getHashBatch = `-- name: GetHashBatch :many
DELETE
FROM hash
WHERE hash IN (SELECT hash FROM hash LIMIT $1)
    RETURNING hash
`

func (q *Queries) GetHashBatch(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getHashBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniqueNumbers = `-- name: GetUniqueNumbers :many
SELECT nextval('unique_number_seq')
FROM generate_series(1, $1)
`

func (q *Queries) GetUniqueNumbers(ctx context.Context, generateSeries int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUniqueNumbers, generateSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var nextval int64
		if err := rows.Scan(&nextval); err != nil {
			return nil, err
		}
		items = append(items, nextval)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
